### PR TITLE
Fix backslash escaping at the end of quoted string.

### LINKED ISSUE #48: Backslash escapes not working properly at the end of quoted strings
@ziggythehamster pointed out via Terraform's Gitter chat that there's still some quirkiness with backslash escapes in HIL.

Consider this example:

```hcl
resource "null_resource" "foo" {
  triggers = {
    thing = "${replace(var.thing, "\\", "/")}"
  }
}
```

This produces a syntax error in the HIL parser:

```
Error loading config: Error loading try.tf: Error reading config for null_resource[foo]: parse error at 1:31: expected "${" but found invalid sequence ")}"
```

It seems that the `\\"` sequence is escaping the quote, rather than escaping the backslash as expected. Adding a space before the quote mark seems to get past the parse error. Presumably this is a logic error in the escape handling.

### PR DESCRIPTION
**Pull request by VladRassokhin**
Fixes #48

### CODE REVIEW

**Comment by VladRassokhin** [comment]
@apparentlymart Please take a look.

**Comment by VladRassokhin** [comment]
@apparentlymart Could you please merge this?

**Comment by apparentlymart** [comment]
Sorry... HIL stuff isn't on my usual radar so I missed this one. But I've put it on my list and will take a look soon.

**Comment by apparentlymart** [comment]
Sorry for the delay here, @VladRassokhin! This looks good to me, and I've merged it here. We'll also get the vendored version in Terraform upgraded soon.

**Pull request merged**
